version: "3.9"

services:
    php:
        container_name: recipe_finder_backend
        image: php
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT}:80"
        volumes:
          - ./backend:/var/www/html
        environment:
          MYSQL_SERVER: ${MYSQL_SERVER_DO}
          MYSQL_DATABASE: ${MYSQL_DATABASE}
          MYSQL_USER: ${MYSQL_USER}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD}